name: Review and build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - id: install
        name: Install dependencies
        run: yarn install --immutable

      - id: compile
        name: Elm review
        run: yarn review

      - id: test
        name: Build
        run: yarn build
